name: Build

on: [push, pull_request]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install build dependencies
        run: sudo apt install -y build-essential cmake libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libglew-dev libglm-dev zlib1g-dev
      - name: cmake
        run: cmake .
      - name: make
        run: make
